# Final Exercise on pandas

In the last notebooks you have learned a lot of new things, and you have also been able to practice them. Only by practicing will you become more confident in using the methods and hopefully it will stick in your mind better.
Thus, here is another exercise on pandas, in which you are asked to do a few different things with the new tools we learned about (methods for combining records, `pd.cut` and `pivot tables`).

We'll be working with the `wine` datasets that are located in the `data` folder in this day's directory.

1. Read the `winequality-red.csv` data into a `DataFrame`, and the `winequality-white.csv` into another `DataFrame`.

In [3]:
import pandas as pd
import numpy as np

redwine_df = pd.read_csv("data/winequality-red.csv", sep=";")
redwine_df.head()

whitewine_df = pd.read_csv("data/winequality-white.csv", sep=";")
whitewine_df.head(3)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6

2. Double check that you've read them in right by using some of the attributes and methods available on `DataFrames` for getting a general sense of your data.

In [5]:
redwine_df.shape
whitewine_df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

3. I've decided that this month I want to stay away from wines with relatively high alcohol content. To do that, I'm going to avoid any wines that have a greater alcohol content than the mean alcohol content, and you're going to help me do this. To achieve this, let's do the following: 

  * Find the mean alcohol content, separately, for reds and whites.  
  * Create a `Series` that holds whether each row in each `DataFrame` (the reds, and whites) has a higher alcohol content than the mean. 
  * Merge this `Series` onto the `DataFrame`. I can imagine doing this with either a `.join()` or using `pd.concat()`. For practice, do it with both. Note: merges with `Series` work the same way that they work with `DataFrames`.  
  * Return back to me all those rows that will help me stay away from those wines with a higher alcohol content.

In [7]:
#  * Find the mean alcohol content, separately, for reds and whites.  

ave_alc_red = redwine_df["alcohol"].mean()
ave_alc_red

ave_alc_white = whitewine_df["alcohol"].mean()
ave_alc_white

np.float64(10.514267047774602)

In [ ]:
#Create a `Series` that holds whether each row in each `DataFrame` (the reds, and whites) has a higher alcohol content than the mean. 

#redwine_df.eval("higher_than_ave = alcohol > alcohol.mean()")
#whitewine_df.eval("higher_than_ave = alcohol > alcohol.mean()")

red_higher_series = redwine_df["alcohol"] > redwine_df["alcohol"].mean()
red_higher_series
white_higher_series = whitewine_df["alcohol"] > redwine_df["alcohol"].mean()
white_higher_series

0       False
1       False
2       False
3       False
4       False
        ...
4893     True
4894    False
4895    False
4896     True
4897     True
Name: alcohol, Length: 4898, dtype: bool

In [25]:
#Merge this `Series` onto the `DataFrame`. I can imagine doing this with either a `.join()` or using `pd.concat()`. 
# For practice, do it with both. Note: merges with `Series` work the same way that they work with `DataFrames`.  

red_higher_series.name = "higher_than_ave"
white_higher_series.name = "higher_than_ave"

red_joined = redwine_df.join(red_higher_series)
red_joined

white_joined = whitewine_df.join(white_higher_series)
white_joined

red_concat = pd.concat([redwine_df, red_higher_series], axis=1)
red_concat
white_concat = pd.concat([whitewine_df, white_higher_series], axis=1)

In [26]:
# Return back to me all those rows that will help me stay away from those wines with a higher alcohol content.

red_concat.query("higher_than_ave == False")
white_concat.query("higher_than_ave == False")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,higher_than_ave
0,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6,False
1,6.3,0.300,0.34,1.60,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,False
2,8.1,0.280,0.40,6.90,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,False
3,7.2,0.230,0.32,8.50,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,False
4,7.2,0.230,0.32,8.50,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4888,6.8,0.220,0.36,1.20,0.052,38.0,127.0,0.99330,3.04,0.54,9.2,5,False
4889,4.9,0.235,0.27,11.75,0.030,34.0,118.0,0.99540,3.07,0.50,9.4,6,False
4892,6.5,0.230,0.38,1.30,0.032,29.0,112.0,0.99298,3.29,0.54,9.7,5,False
4894,6.6,0.320,0.36,8.00,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,False
4895,6.5,0.240,0.19,1.20,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,False

4. Let's say that I want to get started on cutting back next month. This time, though, I want to focus on staying away from those wines with a high acidity. Specifically, I want to stay away from those wines that are in the highest bin of fixed acidity (highest bin out of 5). You're now going to help me do this. To achieve this, let's do the following: 

 * Separate the rows in each `DataFrame` into 5 equal width bins (not equal to quintiles) based off their fixed acidity. 
 * Merge the resulting `Series` holding these 5 bins onto the original `DataFrame`. I can imagine also doing this with either `.join()` or using `pd.concat()`. Try doing it with both for practice. 
 * Return back to me all those rows that are **not in** the top bin in terms of fixed acidity.

In [53]:
# Separate the rows in each `DataFrame` into 5 equal width bins (not equal to quintiles) based off their fixed acidity.

#red_concat["fixed_acidity_bins"] = pd.cut(red_concat['fixed acidity'], bins=5, labels=["very low", "low", "medium", "high", "very high"])

#red_concat.head()

#red_joined_bins = red_concat.join(acidity_bins)
#red_joined_bins.head()

acidity_bins_white = pd.cut(white_concat['fixed acidity'], bins=5, labels=["very low", "low", "medium", "high", "very high"])
acidity_bins_white.name = "acidity_bins"

white_joined_bins = white_concat.join(acidity_bins_white)
white_joined_bins

red_concat.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,higher_than_ave,fixed_acidity_bins
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,False,low
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,False,low
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,False,low
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,False,medium
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,False,low

In [65]:
#Return back to me all those rows that are **not in** the top bin in terms of fixed acidity. 

white_joined_bins.query("acidity_bins != 'very high'")
white_joined_bins.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,higher_than_ave,acidity_bins
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,False,low
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,False,low
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,False,medium
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,False,low
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,False,low

5. Let's say that I now want to know how much my decision to avoid those wines with higher `alcohol` content is going to limit the `quality` of wines that I can drink. To figure this out, I want to know a couple of things: 

 * The average `alcohol` content for those reds above the mean `alcohol` level, by quality.
 * The average `alcohol` content for those whites above the mean `alcohol` level, by quality. 
 
 Use a `pivot table` to solve this.

In [73]:
red_concat[red_concat["higher_than_ave"]].groupby("quality")["alcohol"].mean()
#white_joined_bins.query("higher_than_ave == True").groupby("quality")["alcohol"].mean()

quality
3    10.866667
4    11.295000
5    11.088686
6    11.437214
7    11.708236
8    12.368750
Name: alcohol, dtype: float64

In [72]:
pd.pivot_table(red_concat[red_concat["higher_than_ave"]], values='alcohol', index='quality')

           alcohol
quality
3        10.866667
4        11.295000
5        11.088686
6        11.437214
7        11.708236
8        12.368750

6. Now, do the same for my decision to avoid wines with a high acidity next month: 

 * Find the average `alcohol` content for reds, by `quality` and `fixed acidity` bin. 
 * Find the average `alcohol` content for whites, by `quality` and `fixed acidity` bin. 
 
  Use a `pivot table` to solve this.

In [78]:
pd.pivot_table(red_concat, values='alcohol', index=['quality', "fixed_acidity_bins"])
pd.pivot_table(white_joined_bins, values='alcohol', index=['quality', "acidity_bins"])

C:\Users\Inbal\AppData\Local\Temp\ipykernel_31856\3990637164.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(red_concat, values='alcohol', index=['quality', "fixed_acidity_bins"])
C:\Users\Inbal\AppData\Local\Temp\ipykernel_31856\3990637164.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(white_joined_bins, values='alcohol', index=['quality', "acidity_bins"])

                        alcohol
quality acidity_bins
3       very low       9.850000
        low           10.472727
        medium        10.540000
        high           9.650000
4       very low      10.786364
        low           10.102564
        medium        10.126471
        high           9.900000
5       very low      10.136635
        low            9.732173
        medium        10.176452
        high           9.700000
6       very low      10.902765
        low           10.529056
        medium        10.635247
        high           9.500000
        very high     11.100000
7       very low      12.021405
        low           11.303724
        medium        10.988679
8       very low      12.403030
        low           11.486364
        medium        11.080000
9       low           12.625000
        medium        10.400000